<script setup>
import { ref, onMounted } from "vue";
import { useHead } from "@unhead/vue";

useHead({
  title: "Mehedi Hasan | Full-Stack Developer & SaaS Innovator",
  meta: [
    {
      name: "description",
      content:
        "Mehedi Hasan is a full-stack developer specializing in Laravel, Node.js, Vue.js, and scalable SaaS solutions. Explore his projects and expertise.",
    },
  ],
});

const isLoaded = ref(false);
const activeProject = ref(null);

const projects = [
  {
    id: "countdown-builder",
    title: "Countdown Builder",
    url: "https://countdownbuilder.com",
    tagline: "Email countdown timers that convert",
    description:
      "Supercharge your email campaigns with dynamic countdowns. Images are generated by a custom Rust service, compiled to WASM for the builder interface. Craft visually stunning, time-sensitive emails that boost conversions.",
    tags: ["Laravel", "Rust", "WASM", "SaaS"],
    image: "https://countdownbuilder.com/wp-content/uploads/2025/08/pulsing-animation-countdown-timer.gif",
    featured: true,
  },
  {
    id: "umamiqr",
    title: "UmamiQR",
    url: "https://umamiqr.com",
    tagline: "AI-powered QR menus for restaurants",
    description:
      "A free digital QR menu platform for restaurants, cafes, and food trucks. AI-powered menu management through natural language, instant QR codes, real-time updates, and built-in analytics. Sub-600ms load times via Redis and CDN.",
    tags: ["Laravel", "Vue.js", "AI", "Redis"],
    featured: true,
  },
  {
    id: "ogdynamic",
    title: "OG Dynamic",
    url: "https://ogdynamic.com",
    tagline: "Dynamic OG images for ecommerce",
    description:
      "Generate product OG images with branded pricing, product photos, and share-ready layouts. Image generation powered by a custom Rust service for high performance. Create consistent social previews across X, LinkedIn, Facebook, Slack, and iMessage using reusable templates.",
    tags: ["Laravel", "Rust", "E-commerce", "Templates"],
    featured: true,
  },
  {
    id: "md-notes",
    title: "MD Notes",
    url: "https://codecanyon.net/item/md-notes-note-taking-apps/47341309",
    tagline: "Markdown note-taking for Windows",
    description:
      "A markdown-based note-taking desktop app for Windows with syntax highlighting, code snippets, mermaid diagrams, live preview, dark mode, full-text search, and offline storage via SQLite.",
    tags: ["Rust", "Desktop", "Windows"],
    featured: false,
  },
  {
    id: "wp-query-builder",
    title: "WP Query Builder",
    url: "https://github.com/mehedimi/wp-query-builder",
    tagline: "WordPress database queries made elegant",
    description:
      "A Composer package that simplifies WordPress database query writing. Run simple commands to interact with your database efficiently.",
    tags: ["PHP", "WordPress", "Composer"],
  },
  {
    id: "laravel-dynamodb",
    title: "Laravel DynamoDB",
    url: "https://github.com/mehedimi/laravel-dynamodb",
    tagline: "Eloquent-style DynamoDB for Laravel",
    description:
      "A package for Laravel that provides fluent DynamoDB interaction with full Eloquent support. Perform CRUD operations, batch operations, and pagination with ease.",
    tags: ["Laravel", "AWS DynamoDB", "PHP"],
  },
  {
    id: "laravel-amp-mail",
    title: "Laravel AMP Mail",
    url: "https://github.com/mehedimi/laravel-amp-mail",
    tagline: "AMP email support for Laravel",
    description:
      "Send emails with AMP support alongside HTML or Text versions. Graceful fallback ensures users without AMP-capable clients still receive your message.",
    tags: ["Laravel", "PHP", "Email"],
  },
  {
    id: "typing-master",
    title: "Typing Master for Developers",
    url: "https://typing-v3.netlify.app",
    tagline: "Practice typing real code",
    description:
      "A typing app designed for developers. Practice typing expressions from various programming languages rather than random paragraphs.",
    tags: ["Vue.js", "JavaScript", "Education"],
  },
  {
    id: "six-mens-morris",
    title: "Six Men's Morris",
    url: "https://path-game.herokuapp.com",
    tagline: "A path matching game",
    description:
      "A classic path matching game. Test your strategy and spatial reasoning skills in this engaging puzzle game.",
    tags: ["Game", "JavaScript"],
  },
  {
    id: "product-watcher",
    title: "Product Watcher",
    url: "https://wordpress.org/plugins/product-watcher",
    tagline: "Real-time viewer counts for WooCommerce",
    description:
      "A WordPress plugin that displays product viewer counts in your WooCommerce store in real time.",
    tags: ["WordPress", "WooCommerce", "PHP"],
  },
];

onMounted(() => {
  setTimeout(() => {
    isLoaded.value = true;
  }, 100);
});
</script>

<template>
  <div
    class="min-h-screen bg-stone-50 text-stone-800"
    :class="{ 'loading-state': !isLoaded }"
  >
    <!-- Noise texture overlay -->
    <div class="noise-overlay"></div>

    <!-- Hero Section -->
    <header
      class="relative min-h-screen flex items-center justify-center overflow-hidden"
    >
      <!-- Background decoration -->
      <div class="absolute inset-0 overflow-hidden">
        <div class="hero-blob hero-blob-1"></div>
        <div class="hero-blob hero-blob-2"></div>
        <div class="hero-grid"></div>
      </div>

      <div class="relative z-10 text-center px-6 max-w-4xl mx-auto">
        <div class="mb-8 inline-flex items-center gap-2 px-4 py-2 rounded-full bg-green-50/80 backdrop-blur-sm border border-green-200">
          <span class="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
          <span class="text-sm font-medium text-green-700">Available for projects</span>
        </div>

        <h1 class="hero-title text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight mb-6">
          <span class="block text-stone-900">Mehedi</span>
          <span class="block text-transparent bg-clip-text bg-gradient-to-r from-amber-600 via-orange-500 to-amber-700">Hasan</span>
        </h1>

        <p class="hero-subtitle text-xl md:text-2xl text-stone-600 mb-4 font-light">
          Full-Stack Developer &amp; SaaS Builder
        </p>

        <p class="hero-description text-lg text-stone-500 max-w-2xl mx-auto mb-12">
          Crafting scalable solutions with Laravel, Node.js, and Vue.js.
          Building products that solve real problems.
        </p>

        <div class="hero-cta flex flex-wrap gap-4 justify-center">
          <a
            href="#projects"
            class="group relative px-8 py-4 bg-stone-900 text-stone-50 rounded-full font-medium overflow-hidden transition-all duration-300 hover:scale-105"
          >
            <span class="relative z-10">View Projects</span>
            <div class="absolute inset-0 bg-gradient-to-r from-amber-600 to-orange-500 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </a>
          <a
            href="https://www.fiverr.com/mehedi_mi"
            target="_blank"
            rel="noopener"
            class="px-8 py-4 border-2 border-green-300 text-green-700 rounded-full font-medium hover:bg-green-50 hover:border-green-400 transition-all duration-300"
          >
            Hire Me
          </a>
        </div>
      </div>

      <!-- Scroll indicator -->
      <div class="absolute bottom-8 left-1/2 -translate-x-1/2">
        <div class="scroll-indicator">
          <span class="text-xs text-stone-400 uppercase tracking-widest">Scroll</span>
        </div>
      </div>
    </header>

    <!-- About Section -->
    <section class="py-32 px-6 relative">
      <div class="max-w-6xl mx-auto">
        <div class="grid lg:grid-cols-2 gap-16 items-center">
          <div class="relative">
            <div class="absolute -top-8 -left-8 w-72 h-72 bg-amber-200/30 rounded-full blur-3xl"></div>
            <div class="relative grid grid-cols-2 gap-4">
              <div class="space-y-4">
                <div class="bg-amber-100 rounded-2xl p-6 aspect-square flex items-center justify-center">
                  <svg class="w-12 h-12 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/>
                  </svg>
                </div>
                <div class="bg-stone-200 rounded-2xl p-6 aspect-square flex items-center justify-center">
                  <svg class="w-12 h-12 text-stone-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M13 10V3L4 14h7v7l9-11h-7z"/>
                  </svg>
                </div>
              </div>
              <div class="space-y-4 mt-8">
                <div class="bg-gradient-to-br from-amber-100 to-orange-100 rounded-2xl p-6 aspect-square flex items-center justify-center">
                  <svg class="w-12 h-12 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064"/>
                  </svg>
                </div>
                <div class="bg-stone-900 rounded-2xl p-6 aspect-square flex items-center justify-center">
                  <svg class="w-12 h-12 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"/>
                  </svg>
                </div>
              </div>
            </div>
          </div>

          <div>
            <span class="text-amber-600 font-medium uppercase tracking-wider text-sm">About Me</span>
            <h2 class="text-4xl md:text-5xl font-bold mt-2 mb-6 text-stone-900">
              Building with purpose
            </h2>
            <div class="prose prose-stone prose-lg">
              <p class="text-stone-600 leading-relaxed">
                As-salamualikum! I'm Mehedi Hasan, a full-stack developer and open source contributor based in Bangladesh. I specialize in building scalable web applications and SaaS products that solve real problems.
              </p>
              <p class="text-stone-600 leading-relaxed">
                My core stack is PHP with Laravel, but I'm equally comfortable working with Node.js and Vue.js for the frontend. I'm passionate about creating tools that developers and businesses actually need.
              </p>
              <p class="text-stone-600 leading-relaxed">
                Currently building <a href="https://countdownbuilder.com" class="text-amber-600 font-medium hover:text-amber-700">Countdown Builder</a> — an email countdown timer tool for marketing campaigns.
              </p>
            </div>

            <div class="mt-8 flex flex-wrap gap-3">
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">Laravel</span>
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">Vue.js</span>
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">Node.js</span>
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">Rust</span>
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">AWS</span>
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">PostgreSQL</span>
              <span class="px-4 py-2 bg-stone-100 rounded-full text-sm font-medium text-stone-700">Redis</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Projects Section -->
    <section id="projects" class="py-32 px-6 bg-stone-100">
      <div class="max-w-6xl mx-auto">
        <div class="text-center mb-16">
          <span class="text-amber-600 font-medium uppercase tracking-wider text-sm">Portfolio</span>
          <h2 class="text-4xl md:text-5xl font-bold mt-2 text-stone-900">
            Featured Projects
          </h2>
          <p class="text-stone-500 mt-4 max-w-2xl mx-auto">
            A selection of projects I've built — from SaaS products to open source packages
          </p>
        </div>

        <!-- Featured Projects (3 columns) -->
        <div class="grid md:grid-cols-3 gap-6 mb-12">
          <a
            v-for="project in projects.filter(p => p.featured)"
            :key="project.id"
            :href="project.url"
            target="_blank"
            rel="noopener"
            class="group featured-card bg-white rounded-3xl p-6 border border-stone-200 hover:border-amber-200 hover:shadow-xl hover:shadow-amber-100/50 transition-all duration-500"
          >
            <div class="flex items-start justify-between mb-4">
              <div class="w-12 h-12 bg-gradient-to-br from-amber-100 to-orange-100 rounded-xl flex items-center justify-center">
                <svg class="w-6 h-6 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
                </svg>
              </div>
              <svg class="w-5 h-5 text-stone-300 group-hover:text-amber-500 group-hover:translate-x-1 group-hover:-translate-y-1 transition-all duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 17L17 7M17 7H7M17 7V17"/>
              </svg>
            </div>

            <h3 class="text-xl font-bold text-stone-900 mb-2 group-hover:text-amber-600 transition-colors duration-300">
              {{ project.title }}
            </h3>
            <p class="text-sm font-medium text-amber-600 mb-3">{{ project.tagline }}</p>
            <p class="text-stone-500 text-sm leading-relaxed mb-4">
              {{ project.description }}
            </p>

            <div class="flex flex-wrap gap-2">
              <span
                v-for="tag in project.tags"
                :key="tag"
                class="px-3 py-1 bg-stone-50 rounded-full text-xs font-medium text-stone-600"
              >
                {{ tag }}
              </span>
            </div>
          </a>
        </div>

        <!-- Other Projects (2 columns) -->
        <div class="grid md:grid-cols-2 gap-6">
          <a
            v-for="project in projects.filter(p => !p.featured)"
            :key="project.id"
            :href="project.url"
            target="_blank"
            rel="noopener"
            class="group other-card bg-white rounded-2xl p-6 border border-stone-200 hover:border-amber-200 hover:shadow-lg transition-all duration-300"
          >
            <div class="flex items-start justify-between">
              <div class="flex-1">
                <h3 class="text-lg font-bold text-stone-900 mb-1 group-hover:text-amber-600 transition-colors duration-300">
                  {{ project.title }}
                </h3>
                <p class="text-sm text-amber-600 font-medium mb-2">{{ project.tagline }}</p>
                <p class="text-stone-500 text-sm leading-relaxed">
                  {{ project.description }}
                </p>
              </div>
              <svg class="w-5 h-5 text-stone-300 group-hover:text-amber-500 transition-colors duration-300 ml-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 17L17 7M17 7H7M17 7V17"/>
              </svg>
            </div>

            <div class="flex flex-wrap gap-2 mt-4">
              <span
                v-for="tag in project.tags"
                :key="tag"
                class="px-2 py-1 bg-stone-50 rounded-full text-xs font-medium text-stone-500"
              >
                {{ tag }}
              </span>
            </div>
          </a>
        </div>
      </div>
    </section>

    <!-- Contact Section -->
    <section class="py-32 px-6 relative overflow-hidden">
      <div class="absolute inset-0">
        <div class="absolute bottom-0 left-1/4 w-96 h-96 bg-amber-200/20 rounded-full blur-3xl"></div>
        <div class="absolute top-1/4 right-1/4 w-64 h-64 bg-orange-200/20 rounded-full blur-3xl"></div>
      </div>

      <div class="relative max-w-2xl mx-auto text-center">
        <span class="text-amber-600 font-medium uppercase tracking-wider text-sm">Contact</span>
        <h2 class="text-4xl md:text-5xl font-bold mt-2 mb-4 text-stone-900">
          Let's work together
        </h2>
        <p class="text-stone-500 mb-8">
          Have a project in mind? I'd love to hear about it. Drop me an email and let's create something great.
        </p>

        <a
          href="mailto:me@mehedi.im"
          class="group inline-flex items-center gap-3 px-8 py-4 bg-stone-900 text-stone-50 rounded-full font-medium hover:bg-amber-600 transition-all duration-300"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
          </svg>
          me@mehedi.im
          <svg class="w-4 h-4 group-hover:translate-x-1 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
          </svg>
        </a>

        <div class="mt-12 flex justify-center gap-6">
          <a
            href="https://twitter.com/mehedimi"
            target="_blank"
            rel="noopener"
            class="w-12 h-12 bg-stone-100 rounded-full flex items-center justify-center text-stone-500 hover:bg-amber-100 hover:text-amber-600 transition-all duration-300"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
            </svg>
          </a>
          <a
            href="https://github.com/mehedimi"
            target="_blank"
            rel="noopener"
            class="w-12 h-12 bg-stone-100 rounded-full flex items-center justify-center text-stone-500 hover:bg-amber-100 hover:text-amber-600 transition-all duration-300"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/>
            </svg>
          </a>
          <a
            href="https://www.linkedin.com/in/mehedimi/"
            target="_blank"
            rel="noopener"
            class="w-12 h-12 bg-stone-100 rounded-full flex items-center justify-center text-stone-500 hover:bg-amber-100 hover:text-amber-600 transition-all duration-300"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
            </svg>
          </a>
          </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-8 px-6 border-t border-stone-200">
      <div class="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
        <p class="text-sm text-stone-400">
          Built with Vue.js + Tailwind CSS
        </p>
        <p class="text-sm text-stone-400">
          © {{ new Date().getFullYear() }} Mehedi Hasan. All rights reserved.
        </p>
      </div>
    </footer>
  </div>
</template>

<style>
/* Noise overlay */
.noise-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  z-index: 9999;
  opacity: 0.03;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E");
}

/* Hero animations */
.hero-blob {
  position: absolute;
  border-radius: 50%;
  filter: blur(80px);
  opacity: 0.5;
  animation: float 20s ease-in-out infinite;
}

.hero-blob-1 {
  width: 600px;
  height: 600px;
  background: radial-gradient(circle, rgba(251, 191, 36, 0.3) 0%, transparent 70%);
  top: -200px;
  right: -100px;
}

.hero-blob-2 {
  width: 400px;
  height: 400px;
  background: radial-gradient(circle, rgba(251, 146, 60, 0.2) 0%, transparent 70%);
  bottom: -100px;
  left: -100px;
  animation-delay: -10s;
}

.hero-grid {
  position: absolute;
  inset: 0;
  background-image:
    linear-gradient(rgba(251, 191, 36, 0.03) 1px, transparent 1px),
    linear-gradient(90deg, rgba(251, 191, 36, 0.03) 1px, transparent 1px);
  background-size: 60px 60px;
}

@keyframes float {
  0%, 100% { transform: translate(0, 0) scale(1); }
  25% { transform: translate(30px, -30px) scale(1.05); }
  50% { transform: translate(-20px, 20px) scale(0.95); }
  75% { transform: translate(20px, 10px) scale(1.02); }
}

/* Scroll indicator */
.scroll-indicator {
  animation: bounce 2s ease-in-out infinite;
}

@keyframes bounce {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(10px); }
}

/* Hero text animations */
.hero-title {
  animation: fadeInUp 0.8s ease-out forwards;
  opacity: 0;
}

.hero-subtitle {
  animation: fadeInUp 0.8s ease-out 0.2s forwards;
  opacity: 0;
}

.hero-description {
  animation: fadeInUp 0.8s ease-out 0.4s forwards;
  opacity: 0;
}

.hero-cta {
  animation: fadeInUp 0.8s ease-out 0.6s forwards;
  opacity: 0;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Loading state */
.loading-state .hero-title,
.loading-state .hero-subtitle,
.loading-state .hero-description,
.loading-state .hero-cta {
  opacity: 0;
}

/* Featured card hover effect */
.featured-card {
  animation: fadeInUp 0.6s ease-out forwards;
  opacity: 0;
}

.featured-card:nth-child(1) { animation-delay: 0.1s; }
.featured-card:nth-child(2) { animation-delay: 0.2s; }
.featured-card:nth-child(3) { animation-delay: 0.3s; }

.featured-card:hover .group-hover\:translate-x-1 {
  transform: translate(4px, -4px);
}

/* Other card animations */
.other-card {
  animation: fadeInUp 0.6s ease-out forwards;
  opacity: 0;
}

.other-card:nth-child(1) { animation-delay: 0.4s; }
.other-card:nth-child(2) { animation-delay: 0.5s; }
.other-card:nth-child(3) { animation-delay: 0.6s; }
.other-card:nth-child(4) { animation-delay: 0.7s; }
.other-card:nth-child(5) { animation-delay: 0.8s; }
.other-card:nth-child(6) { animation-delay: 0.9s; }

/* Prose customization for links */
.prose a {
  color: #d97706;
  text-decoration: none;
  transition: color 0.2s ease;
}

.prose a:hover {
  color: #b45309;
}

/* Custom scrollbar */
::-webkit-scrollbar {
  width: 8px;
}

::-webkit-scrollbar-track {
  background: #f5f5f4;
}

::-webkit-scrollbar-thumb {
  background: #d6d3d1;
  border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
  background: #a8a29e;
}

/* Selection color */
::selection {
  background: rgba(251, 191, 36, 0.3);
  color: #1c1917;
}
</style>
